[package]
name = "koala-transaction-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "*"
rusqlite = "*"
serde = { version = "*", features = ["derive"] }
config = "*"
thiserror = "*"
rand = "*"